### ISSUE TITLE
Migrate to a Persistent SQL Database

### ISSUE THREAD

**Issue by AnishMulay** [AMAPAD/WolfLease#8]
The repository is currently using SQLite as its database, but I want to migrate it to a new persistent SQL database for better scalability and performance.

Steps:
1. Choose a new SQL database (e.g., PostgreSQL, MySQL).
2. Configure the database connection settings.
3. Migrate the existing data from SQLite to the new database.
4. Update the code to work with the new database.

This will ensure we have a more scalable and persistent database solution.

**Comment by AshP-dev** [comment]
A few updates - 

1. Trying to look at other DB options - mainly MySQL / MariaDB as alternatives to SQLite 
2. In settings.py - need to update the DATABASE section. Already added (commented) code below the original section.
3. In Docker-compose - added (commented) code for handling the config.

Currently debugging issues with the original code before migration .

**Comment by AshP-dev** [comment]
The project is too bad overall to prioritize this enhancement. This is a good thing for future groups to work on - hopefully they should work on migrating to better and more modern Databases like MongoDB.
